version: '2.0'
services:
  app:
    build: .
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app
      - ~/.pypirc:/root/.pypirc
    command: bash -c "python manage.py test"
    environment:
      - REDIS_HOST=redis


  redis:
    image: redis:3.2.10-alpine
    ports:
      - 6379:6379
